version: "3.9"

services:
  mongo:
    image: mongo:8
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    
  bot:
    build: .
    container_name: telegram_party_bot
    depends_on:
      - mongo
    env_file:
      - .env
    restart: unless-stopped

volumes:
  mongo_data: